[tool.ruff]
select = ["E4", "E7", "E9", "UP", "F", "I"]
fix = true
fixable = ["I"]
exclude = ["env", "node_modules"]

[tool.ruff.lint.isort]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]
known-first-party = ["core"]
